export const GET_HOBBIES_ASYNC = 'GET_HOBBIES_ASYNC';
export const ADD_HOBBY_ASYNC = 'ADD_HOBBY_ASYNC';
export const GET_HOBBIES = 'GET_HOBBIES';
export const ADD_HOBBY = 'ADD_HOBBY';
export const GET_REQUEST_FAILED = 'GET_REQUEST_FAILED';
export const ADD_REQUEST_FAILED = 'ADD_REQUEST_FAILED';
